{{-- Option 3: Cards everywhere — same fields as mobile card, details visible on both mobile (collapsible) and desktop (always in grid) --}}
<div class="order-item-card group border border-primary-100 rounded-xl overflow-hidden shadow-sm transition-all duration-150 relative"
     :class="{ 'expanded': item._expanded, 'bg-white': item._expanded, 'bg-primary-50/50': !item._expanded }">
    <div class="flex items-center justify-between gap-2 px-3 py-3 cursor-pointer select-none border-b border-primary-100" :class="{ 'bg-primary-50': !item._expanded, 'bg-white': item._expanded }" @click="toggleItem(idx)">
        <div class="flex flex-1 min-w-0 items-center gap-2">
            <span class="font-semibold text-sm text-slate-800 shrink-0" x-show="!item._expanded" x-text="'{{ __('order_form.product_num') }} ' + (idx + 1)"></span>
            <span class="flex-1 font-semibold text-sm text-slate-800 text-center truncate" dir="ltr" x-show="!item._expanded && getItemSite(item)" x-text="getItemSite(item)"></span>
            <span class="flex-1 font-semibold text-sm text-slate-800 truncate" x-show="item._expanded" x-text="itemSummary(idx, true)"></span>
        </div>
        <div class="flex gap-2 items-center shrink-0" @click.stop>
            <button type="button" class="inline-flex items-center justify-center py-1.5 px-2.5 rounded-md text-xs font-semibold bg-primary-500/10 text-primary-500 border border-primary-500/25 hover:bg-primary-500/20 hover:border-primary-500 transition-colors" @click="item._expanded = !item._expanded">
                <span x-show="!item._expanded">{{ __('order_form.show_edit') }}</span>
                <span x-show="item._expanded" x-cloak>{{ __('order_form.hide') }}</span>
            </button>
            <button type="button" class="inline-flex lg:hidden items-center justify-center w-9 h-9 rounded-lg text-slate-400 hover:bg-slate-100 hover:text-red-600 transition-colors" @click="removeItem(idx)" aria-label="{{ __('order_form.remove') }}">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5"><path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" /></svg>
            </button>
            <button type="button" class="hidden lg:inline-flex items-center justify-center py-1.5 px-2.5 rounded-md text-xs font-semibold bg-red-100/30 text-red-600 border border-red-200 hover:bg-red-100 hover:text-red-700 transition-colors" @click="removeItem(idx)">{{ __('order_form.remove') }}</button>
        </div>
    </div>
    {{-- Mobile: collapsible (max-lg:hidden until expanded). Desktop: always visible. Single column layout for alignment. --}}
    <div class="order-item-details p-3 gap-2.5 max-lg:hidden max-lg:group-[.expanded]:flex max-lg:group-[.expanded]:flex-col lg:flex lg:flex-col">
        <div class="order-cell-url"><span class="block text-xs text-slate-500 mb-0.5 font-medium">{{ __('order_form.th_url') }} <span class="order-field-optional">{{ __('order_form.optional') }}</span></span><textarea x-model="item.url" @blur="calcTotals(); saveDraft()" :placeholder="idx === 0 ? '{{ __('order_form.url_placeholder') }}' : ''" rows="1" class="order-form-input overflow-hidden w-full px-3 py-2 border border-primary-100 rounded-lg text-sm bg-white focus:outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/10 resize-none break-words min-h-[2.5rem]" :title="item.url || ''" x-init="$nextTick(() => { if ((item.url || '').trim()) { $el.style.height = 'auto'; $el.style.height = Math.min(Math.max($el.scrollHeight, 40), 130) + 'px'; } else { $el.style.height = '40px'; } const o = $el.scrollHeight > $el.offsetHeight; $el.classList.toggle('overflow-y-auto', o); $el.classList.toggle('scrollbar-hide', o); $el.classList.toggle('overflow-hidden', !o); })" @input="if (item.url.length > 2000) { item.url = item.url.slice(0, 2000); showNotify('error', maxCharsMsg); } if (!(item.url || '').trim()) { $el.style.height = '40px'; $el.classList.remove('overflow-y-auto','scrollbar-hide'); $el.classList.add('overflow-hidden'); return; } $el.style.height = 'auto'; $el.style.height = Math.min(Math.max($el.scrollHeight, 40), 130) + 'px'; const o = $el.scrollHeight > $el.offsetHeight; $el.classList.toggle('overflow-y-auto', o); $el.classList.toggle('scrollbar-hide', o); $el.classList.toggle('overflow-hidden', !o);"></textarea></div>
        <div class="order-cell-col"><span class="block text-xs text-slate-500 mb-0.5 font-medium">{{ __('order_form.th_color') }} <span class="order-field-optional">{{ __('order_form.optional') }}</span></span><textarea x-model="item.color" @blur="saveDraft()" rows="1" class="order-form-input overflow-hidden w-full px-3 py-2 border border-primary-100 rounded-lg text-sm bg-white focus:outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/10 resize-none break-words min-h-[2.5rem]" :title="item.color || ''" x-init="$nextTick(() => { if ((item.color || '').trim()) { $el.style.height = 'auto'; $el.style.height = Math.min(Math.max($el.scrollHeight, 40), 130) + 'px'; } else { $el.style.height = '40px'; } const o = $el.scrollHeight > $el.offsetHeight; $el.classList.toggle('overflow-y-auto', o); $el.classList.toggle('scrollbar-hide', o); $el.classList.toggle('overflow-hidden', !o); })" @input="if (item.color.length > 2000) { item.color = item.color.slice(0, 2000); showNotify('error', maxCharsMsg); } if (!(item.color || '').trim()) { $el.style.height = '40px'; $el.classList.remove('overflow-y-auto','scrollbar-hide'); $el.classList.add('overflow-hidden'); return; } $el.style.height = 'auto'; $el.style.height = Math.min(Math.max($el.scrollHeight, 40), 130) + 'px'; const o = $el.scrollHeight > $el.offsetHeight; $el.classList.toggle('overflow-y-auto', o); $el.classList.toggle('scrollbar-hide', o); $el.classList.toggle('overflow-hidden', !o);"></textarea></div>
        <div class="order-cell-siz"><span class="block text-xs text-slate-500 mb-0.5 font-medium">{{ __('order_form.th_size') }} <span class="order-field-optional">{{ __('order_form.optional') }}</span></span><textarea x-model="item.size" @blur="saveDraft()" rows="1" class="order-form-input overflow-hidden w-full px-3 py-2 border border-primary-100 rounded-lg text-sm bg-white focus:outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/10 resize-none break-words min-h-[2.5rem]" :title="item.size || ''" x-init="$nextTick(() => { if ((item.size || '').trim()) { $el.style.height = 'auto'; $el.style.height = Math.min(Math.max($el.scrollHeight, 40), 130) + 'px'; } else { $el.style.height = '40px'; } const o = $el.scrollHeight > $el.offsetHeight; $el.classList.toggle('overflow-y-auto', o); $el.classList.toggle('scrollbar-hide', o); $el.classList.toggle('overflow-hidden', !o); })" @input="if (item.size.length > 2000) { item.size = item.size.slice(0, 2000); showNotify('error', maxCharsMsg); } if (!(item.size || '').trim()) { $el.style.height = '40px'; $el.classList.remove('overflow-y-auto','scrollbar-hide'); $el.classList.add('overflow-hidden'); return; } $el.style.height = 'auto'; $el.style.height = Math.min(Math.max($el.scrollHeight, 40), 130) + 'px'; const o = $el.scrollHeight > $el.offsetHeight; $el.classList.toggle('overflow-y-auto', o); $el.classList.toggle('scrollbar-hide', o); $el.classList.toggle('overflow-hidden', !o);"></textarea></div>
        <div class="order-cell-qty"><span class="block text-xs text-slate-500 mb-0.5 font-medium">{{ __('order_form.th_qty') }} <span class="order-field-optional">{{ __('order_form.optional') }}</span></span><textarea x-model="item.qty" @input="convertArabicNums($event); if (item.qty.length > 2000) { item.qty = item.qty.slice(0, 2000); showNotify('error', maxCharsMsg); } if (!(item.qty || '').trim()) { $el.style.height = '40px'; $el.classList.remove('overflow-y-auto','scrollbar-hide'); $el.classList.add('overflow-hidden'); return; } $el.style.height = 'auto'; $el.style.height = Math.min(Math.max($el.scrollHeight, 40), 130) + 'px'; const o = $el.scrollHeight > $el.offsetHeight; $el.classList.toggle('overflow-y-auto', o); $el.classList.toggle('scrollbar-hide', o); $el.classList.toggle('overflow-hidden', !o);" @blur="calcTotals(); saveDraft()" placeholder="1" rows="1" dir="rtl" class="order-form-input overflow-hidden w-full px-3 py-2 border border-primary-100 rounded-lg text-sm bg-white focus:outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/10 resize-none break-words min-h-[2.5rem]" :title="item.qty || ''" x-init="$nextTick(() => { if ((item.qty || '').trim()) { $el.style.height = 'auto'; $el.style.height = Math.min(Math.max($el.scrollHeight, 40), 130) + 'px'; } else { $el.style.height = '40px'; } const o = $el.scrollHeight > $el.offsetHeight; $el.classList.toggle('overflow-y-auto', o); $el.classList.toggle('scrollbar-hide', o); $el.classList.toggle('overflow-hidden', !o); })"></textarea></div>
        <div class="order-cell-prc"><span class="block text-xs text-slate-500 mb-0.5 font-medium">{{ __('order_form.th_price_per_unit') }} <span class="order-field-optional">{{ __('order_form.optional') }}</span></span><input type="text" x-model="item.price" @input="convertArabicNums($event)" @blur="calcTotals(); saveDraft()" inputmode="decimal" placeholder="{{ __('placeholder.amount') }}" class="order-form-input w-full px-3 py-2 min-w-[4ch] border border-primary-100 rounded-lg text-sm bg-white h-10 focus:outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/10"></div>
        <div class="order-cell-cur"><span class="block text-xs text-slate-500 mb-0.5 font-medium">{{ __('order_form.th_currency') }} <span class="order-field-optional">{{ __('order_form.optional') }}</span></span><select x-model="item.currency" @change="onCurrencyChange(idx)" @blur="calcTotals(); saveDraft()" class="order-form-input w-full px-3 py-2 border border-primary-100 rounded-lg text-sm bg-white h-10 focus:outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/10" :title="currencyList[item.currency]?.label || ''"><template x-for="(cur, code) in currencyList" :key="code"><option :value="code" :title="cur.symbol ? (cur.label + ' (' + cur.symbol + ')') : cur.label" x-text="cur.label || code" :selected="code === item.currency"></option></template></select></div>
        <div class="order-cell-not"><span class="block text-xs text-slate-500 mb-0.5 font-medium">{{ __('order_form.th_notes') }} <span class="order-field-optional">{{ __('order_form.optional') }}</span></span><textarea x-model="item.notes" @blur="saveDraft()" :placeholder="idx === 0 ? '{{ __('order_form.notes_placeholder') }}' : ''" rows="1" class="order-form-input overflow-hidden w-full px-3 py-2 border border-primary-100 rounded-lg text-sm bg-white focus:outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/10 resize-none break-words min-h-[2.5rem]" :title="item.notes || ''" x-init="$nextTick(() => { if ((item.notes || '').trim()) { $el.style.height = 'auto'; $el.style.height = Math.min(Math.max($el.scrollHeight, 40), 130) + 'px'; } else { $el.style.height = '40px'; } const o = $el.scrollHeight > $el.offsetHeight; $el.classList.toggle('overflow-y-auto', o); $el.classList.toggle('scrollbar-hide', o); $el.classList.toggle('overflow-hidden', !o); })" @input="if (item.notes.length > 2000) { item.notes = item.notes.slice(0, 2000); showNotify('error', maxCharsMsg); } if (!(item.notes || '').trim()) { $el.style.height = '40px'; $el.classList.remove('overflow-y-auto','scrollbar-hide'); $el.classList.add('overflow-hidden'); return; } $el.style.height = 'auto'; $el.style.height = Math.min(Math.max($el.scrollHeight, 40), 130) + 'px'; const o = $el.scrollHeight > $el.offsetHeight; $el.classList.toggle('overflow-y-auto', o); $el.classList.toggle('scrollbar-hide', o); $el.classList.toggle('overflow-hidden', !o);"></textarea></div>
        <div class="order-optional-section order-upload-container">
            <span class="block text-xs text-slate-500 mb-0.5 font-medium">{{ __('order_form.th_files') }} <span class="order-field-optional">{{ __('order_form.optional') }}</span></span>
            <div class="flex items-center gap-2 flex-wrap">
                <template x-for="(f, fi) in (item._files || [])" :key="'mfile-'+idx+'-'+fi">
                    <div class="flex items-center gap-1">
                        <div class="relative w-11 h-11 shrink-0 rounded-md overflow-hidden border border-slate-200 cursor-pointer"
                             @click="openFileOrZoom(f)">
                            <template x-if="f.preview"><img :src="f.preview" class="w-full h-full object-cover block cursor-pointer" @click.stop="openFileOrZoom(f)" alt=""></template>
                            <template x-if="!f.preview && f.fileType === 'img'"><div class="w-full h-full flex items-center justify-center bg-slate-100 text-slate-400 text-[10px] pointer-events-none">...</div></template>
                            <template x-if="!f.preview && f.fileType === 'pdf'"><div class="w-full h-full flex items-center justify-center bg-red-100 text-red-500 text-[10px] font-bold pointer-events-none">PDF</div></template>
                            <template x-if="!f.preview && f.fileType === 'xls'"><div class="w-full h-full flex items-center justify-center bg-green-100 text-green-600 text-[10px] font-bold pointer-events-none">XLS</div></template>
                            <template x-if="!f.preview && f.fileType === 'doc'"><div class="w-full h-full flex items-center justify-center bg-blue-100 text-blue-600 text-[10px] font-bold pointer-events-none">DOC</div></template>
                            <button type="button" class="absolute top-0 start-0 w-4 h-4 bg-red-500/90 text-white border-none rounded-full text-[10px] cursor-pointer flex items-center justify-center z-10" @click.stop="removeFile(idx, fi)">×</button>
                        </div>
                        <template x-if="f.uploadProgress !== null && f.uploadProgress !== undefined"><div class="w-12 h-1 bg-slate-100 rounded-sm overflow-hidden"><div class="h-full bg-slate-400 rounded-sm transition-[width] duration-200" :style="'width:' + f.uploadProgress + '%'"></div></div></template>
                    </div>
                </template>
                <template x-if="(item._files || []).length < maxImagesPerItem && totalFileCount() < maxImagesPerOrder">
                    <span class="inline-flex">
                        <input type="file" :id="'order-file-option3-' + idx" class="hidden" multiple
                               accept="{{ implode(',', $allowedMimeTypes ?? allowed_upload_mime_types()) }}"
                               @change="handleFileSelect($event, idx)">
                        <label :for="'order-file-option3-' + idx"
                               @click="if (!isLoggedIn) { $event.preventDefault(); $wire.openLoginModalForAttach(); }"
                               class="border border-dashed border-primary-100 text-slate-500 bg-primary-50 py-2 px-3 rounded-md text-xs font-medium cursor-pointer inline-flex items-center justify-center hover:border-primary-500 hover:text-primary-500 transition-colors">{{ __('order_form.attach') }}</label>
                    </span>
                </template>
                <div class="text-[0.7rem] text-stone-400 w-full">{{ __('order_form.file_info_bulk', ['max' => $maxImagesPerItem]) }}</div>
            </div>
        </div>
    </div>
</div>
